server:
    port: 8080

spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/P2GARCIA
        username: postgres
        password: 123456
        driverClassName: org.postgresql.Driver

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres